"""Initial migration

Revision ID: 25a76fe4ddbc
Revises: 6c2b3d6cdd87
Create Date: 2025-08-07 19:46:17.579063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a76fe4ddbc'
down_revision: Union[str, Sequence[str], None] = '6c2b3d6cdd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
